"""constrain book ratings and add tag seeding

Revision ID: 525b350d19d0
Revises: 53f24572adcc
Create Date: 2026-03-16 17:21:36.489732

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "525b350d19d0"
down_revision = "53f24572adcc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_book_rating_0_5",
            "book_rating IS NULL OR (book_rating >= 0 AND book_rating <= 5)",
        )
        batch_op.create_check_constraint(
            "ck_book_rating_goodreads_0_5",
            "book_rating_goodreads IS NULL OR "
            "(book_rating_goodreads >= 0 AND book_rating_goodreads <= 5)",
        )
        batch_op.alter_column(
            "book_rating",
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "book_rating_goodreads",
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.alter_column(
            "book_rating_goodreads",
            existing_type=sa.Float(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "book_rating",
            existing_type=sa.Float(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.drop_constraint("ck_book_rating_goodreads_0_5", type_="check")
        batch_op.drop_constraint("ck_book_rating_0_5", type_="check")

    # ### end Alembic commands ###
