"""posts from markdown

Revision ID: 53f24572adcc
Revises:
Create Date: 2026-03-16 17:10:15.654708

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "53f24572adcc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("post_slug", sa.String(length=250), nullable=False)
        )
        batch_op.add_column(
            sa.Column("post_source_path", sa.Text(), nullable=False)
        )
        batch_op.create_unique_constraint(
            "uq_post_post_source_path", ["post_source_path"]
        )
        batch_op.create_unique_constraint("uq_post_post_slug", ["post_slug"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_constraint("uq_post_post_slug", type_="unique")
        batch_op.drop_constraint("uq_post_post_source_path", type_="unique")
        batch_op.drop_column("post_source_path")
        batch_op.drop_column("post_slug")

    # ### end Alembic commands ###
