"""Replace Post table with Book review fields, Poem, Quote

Revision ID: b67065c6ea17
Revises: db896f9aa128
Create Date: 2026-07-12 15:59:26.697421

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b67065c6ea17"
down_revision = "db896f9aa128"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "poem",
        sa.Column("poem_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("poem_slug", sa.String(length=250), nullable=False),
        sa.Column("poem_title", sa.Text(), nullable=False),
        sa.Column("poem_body_markdown", sa.Text(), nullable=False),
        sa.Column("poem_author", sa.String(), nullable=False),
        sa.Column("poem_created_at", sa.DateTime(), nullable=True),
        sa.Column("poem_updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("poem_id"),
        sa.UniqueConstraint("poem_slug"),
    )
    op.create_table(
        "quote",
        sa.Column(
            "quote_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("quote_slug", sa.String(length=250), nullable=False),
        sa.Column("quote_text", sa.Text(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.book_id"],
        ),
        sa.PrimaryKeyConstraint("quote_id"),
        sa.UniqueConstraint("quote_slug"),
    )
    op.drop_table("post")
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("review_markdown", sa.Text(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("review_created_at", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("review_updated_at", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.drop_column("review_updated_at")
        batch_op.drop_column("review_created_at")
        batch_op.drop_column("review_markdown")

    op.create_table(
        "post",
        sa.Column("post_id", sa.INTEGER(), nullable=False),
        sa.Column("parent_id", sa.INTEGER(), nullable=True),
        sa.Column("post_slug", sa.VARCHAR(length=250), nullable=False),
        sa.Column("book_id", sa.INTEGER(), nullable=True),
        sa.Column("post_title", sa.TEXT(), nullable=False),
        sa.Column("post_body_markdown", sa.TEXT(), nullable=False),
        sa.Column("post_type", sa.VARCHAR(), nullable=True),
        sa.Column("post_author", sa.VARCHAR(), nullable=False),
        sa.Column("post_updated_at", sa.DATETIME(), nullable=False),
        sa.Column("post_created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.book_id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["post.post_id"], name=op.f("fk_post_parent_id")
        ),
        sa.PrimaryKeyConstraint("post_id"),
        sa.UniqueConstraint("post_slug"),
    )
    op.drop_table("quote")
    op.drop_table("poem")
    # ### end Alembic commands ###
