"""

Revision ID: b9a4f5f9e32e
Revises: f9c8ab9e837f
Create Date: 2026-03-26 15:37:39.474261

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b9a4f5f9e32e"
down_revision = "f9c8ab9e837f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("parent_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_post_parent_id", "post", ["parent_id"], ["post_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_constraint("fk_post_parent_id", type_="foreignkey")
        batch_op.drop_column("parent_id")

    # ### end Alembic commands ###
