"""Allow post_created_at to be nullable

Revision ID: db896f9aa128
Revises: b7e2a4f91c03
Create Date: 2026-04-18 18:33:39.951451

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "db896f9aa128"
down_revision = "b7e2a4f91c03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.drop_column("book_isbn")
        batch_op.drop_column("book_rating_goodreads")

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column(
            "post_created_at", existing_type=sa.DATETIME(), nullable=True
        )

    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_column("tag_description")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("tag_description", sa.TEXT(), nullable=True)
        )

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.alter_column(
            "post_created_at", existing_type=sa.DATETIME(), nullable=False
        )

    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("book_rating_goodreads", sa.FLOAT(), nullable=True)
        )
        batch_op.add_column(sa.Column("book_isbn", sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
