"""initial

Revision ID: f9c8ab9e837f
Revises:
Create Date: 2026-03-20 16:37:32.120794

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f9c8ab9e837f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column(
            "author_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("author_name", sa.String(length=750), nullable=False),
        sa.Column("author_ol_id", sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint("author_id"),
        sa.UniqueConstraint("author_ol_id"),
    )
    op.create_table(
        "book",
        sa.Column("book_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("book_ol_key", sa.String(length=250), nullable=False),
        sa.Column("book_title", sa.String(length=250), nullable=False),
        sa.Column("book_description", sa.Text(), nullable=True),
        sa.Column("book_publication_year", sa.Integer(), nullable=True),
        sa.Column("book_rating_goodreads", sa.Float(), nullable=True),
        sa.Column("book_page_count", sa.Integer(), nullable=True),
        sa.Column("book_isbn", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("book_id"),
        sa.UniqueConstraint("book_ol_key"),
    )
    op.create_table(
        "tag",
        sa.Column("tag_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tag_name", sa.String(), nullable=False),
        sa.Column("tag_description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("tag_id"),
        sa.UniqueConstraint("tag_name"),
    )
    op.create_table(
        "book_author_mapping",
        sa.Column(
            "book_author_mapping_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["author.author_id"],
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.book_id"],
        ),
        sa.PrimaryKeyConstraint("book_author_mapping_id"),
    )
    op.create_table(
        "book_to_tag_map",
        sa.Column(
            "book_to_tag_map_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.book_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.tag_id"],
        ),
        sa.PrimaryKeyConstraint("book_to_tag_map_id"),
    )
    op.create_table(
        "post",
        sa.Column("post_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_slug", sa.String(length=250), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=True),
        sa.Column("post_title", sa.Text(), nullable=False),
        sa.Column("post_body_markdown", sa.Text(), nullable=False),
        sa.Column("post_type", sa.String(), nullable=True),
        sa.Column("post_author", sa.String(), nullable=False),
        sa.Column("post_rating", sa.Float(), nullable=True),
        sa.Column("post_updated_at", sa.DateTime(), nullable=False),
        sa.Column("post_created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "post_rating IS NULL OR (post_rating >= 0 AND post_rating <= 5)",
            name="ck_post_rating_0_5",
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.book_id"],
        ),
        sa.PrimaryKeyConstraint("post_id"),
        sa.UniqueConstraint("post_slug"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post")
    op.drop_table("book_to_tag_map")
    op.drop_table("book_author_mapping")
    op.drop_table("tag")
    op.drop_table("book")
    op.drop_table("author")
    # ### end Alembic commands ###
